# Generated by Django 5.2 on 2025-05-05 20:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[("A", "Admin"), ("E", "Editor"), ("R", "Leitor")],
                        default="R",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VerticalSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                (
                    "cod_categoria",
                    models.CharField(
                        choices=[
                            ("P", "Poder"),
                            ("T", "Tributos"),
                            ("S", "Saude"),
                            ("E", "Energia"),
                            ("W", "Trabalhista"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPlanSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("I", "JOTA Info"), ("P", "JOTA Pro")],
                        default="I",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cd_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_plan",
                        to="api_portal_jota.userschema",
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True, to="api_portal_jota.verticalschema"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoticiaSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("subtitulo", models.CharField(max_length=100)),
                (
                    "imagem",
                    models.FileField(
                        blank=True, null=True, upload_to="noticias/{id_noticia}"
                    ),
                ),
                ("conteudo", models.TextField()),
                ("data_publicacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "Rascunho"), ("P", "Publicado")],
                        default="R",
                        max_length=1,
                    ),
                ),
                ("is_pro", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noticias",
                        to="api_portal_jota.userschema",
                    ),
                ),
                (
                    "verticais",
                    models.ManyToManyField(to="api_portal_jota.verticalschema"),
                ),
            ],
        ),
    ]
