# Generated by Django 5.2 on 2025-05-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplanschema",
            name="cd_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_plan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
