# Generated by Django 5.2 on 2025-05-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0002_alter_userplanschema_cd_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userplanschema",
            old_name="categorias",
            new_name="verticais",
        ),
    ]
