# Generated by Django 5.2 on 2025-05-07 01:04

import api_portal_jota.models.noticia_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0003_rename_categorias_userplanschema_verticais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticiaschema",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api_portal_jota.models.noticia_schema.get_upload_to,
            ),
        ),
    ]
