# Generated by Django 5.2 on 2025-05-07 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0004_alter_noticiaschema_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticiaschema",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noticia",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
