# Generated by Django 5.2 on 2025-05-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0005_alter_noticiaschema_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticiaschema",
            name="data_publicacao",
            field=models.DateTimeField(),
        ),
    ]
