# Generated by Django 5.2 on 2025-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0006_alter_noticiaschema_data_publicacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticiaschema",
            name="imagem_foi_processada",
            field=models.BooleanField(default=False),
        ),
    ]
