# Generated by Django 5.2 on 2025-05-08 00:42

import api_portal_jota.models.noticia_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0007_noticiaschema_imagem_foi_processada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticiaschema",
            name="imagem",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api_portal_jota.models.noticia_schema.get_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="noticiaschema",
            name="status",
            field=models.CharField(
                choices=[
                    ("R", "Rascunho"),
                    ("P", "Publicado"),
                    ("I", "Processando imagem"),
                    ("E", "Erro na imagem"),
                ],
                default="R",
                max_length=1,
            ),
        ),
    ]
