# Generated by Django 5.2 on 2025-05-08 02:23

import api_portal_jota.models.noticia_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0008_alter_noticiaschema_imagem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticiaschema",
            name="imagem",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api_portal_jota.models.noticia_schema.get_upload_to,
                validators=[api_portal_jota.models.noticia_schema.check_image_type],
            ),
        ),
    ]
