# Generated by Django 5.2 on 2025-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0009_alter_noticiaschema_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticiaschema",
            name="imagem_foi_processada",
        ),
        migrations.AddField(
            model_name="noticiaschema",
            name="status_imagem",
            field=models.CharField(
                choices=[
                    ("K", "OK"),
                    ("P", "Pendente"),
                    ("I", "Processando imagem"),
                    ("E", "Erro na imagem"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
