# Generated by Django 5.2 on 2025-05-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_portal_jota", "0010_remove_noticiaschema_imagem_foi_processada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticiaschema",
            name="status",
            field=models.CharField(
                choices=[("R", "Rascunho"), ("P", "Publicado")],
                default="R",
                max_length=1,
            ),
        ),
    ]
