volumes:
  portal_jota_postgres_data:
    name: portal_jota_postgres_data
  portal_jota_redis_data:
    name: portal_jota_redis_data
  portal_jota_rabbitmq_data:
    name: portal_jota_rabbitmq_data

networks:
  portal_jota_postgres_network:
    driver: bridge
  portal_jota_redis_network:
    driver: bridge
  portal_jota_rabbitmq_network:
    driver: bridge

services:
  postgres:
    container_name: portal_jota_postgres
    image: postgres:17.4-alpine
    env_file:
      - postgres/postgres.env
    volumes:
    - portal_jota_postgres_data:/var/lib/postgresql/data
    hostname: portal_jota_postgres
    networks:
      - portal_jota_postgres_network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    container_name: portal_jota_redis
    image: redis:8.0-rc1-alpine3.21
    env_file:
      - redis/redis.env
    volumes:
    - portal_jota_redis_data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    - ./redis/entrypoint.sh:/entrypoint.sh
    hostname: portal_jota_redis
    networks:
      - portal_jota_redis_network
    ports:
      - 6379:6379
    entrypoint: ["/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  rabbitmq:
    container_name: portal_jota_rabbitmq
    image: rabbitmq:4.1.0-management
    env_file:
      - rabbitmq/rabbitmq.env
    volumes:
      - portal_jota_rabbitmq_data:/var/lib/rabbitmq
    hostname: portal_jota_rabbitmq
    networks:
      - portal_jota_rabbitmq_network
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 15s
      timeout: 10s
      retries: 3
  
  web:
    container_name: portal_jota_web
    image: portal_jota:web
    build:
      context: ..
      dockerfile: docker/portal_jota/Dockerfile
    env_file:
      - portal_jota/portal_jota.env
    hostname: portal_jota_web
    networks:
      - portal_jota_postgres_network
      - portal_jota_redis_network
      - portal_jota_rabbitmq_network
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  celery_worker:
    container_name: portal_jota_celery_worker
    image: portal_jota:worker
    build:
      context: ..
      dockerfile: docker/celery_worker/Dockerfile
    env_file:
      - celery_worker/celery_worker.env
    hostname: portal_jota_celery_worker
    networks:
      - portal_jota_postgres_network
      - portal_jota_redis_network
      - portal_jota_rabbitmq_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  celery_beat:
    container_name: portal_jota_celery_beat
    image: portal_jota:beat
    build:
      context: ..
      dockerfile: docker/celery_beat/Dockerfile
    env_file:
      - celery_beat/celery_beat.env
    hostname: portal_jota_celery_beat
    networks:
      - portal_jota_postgres_network
      - portal_jota_redis_network
      - portal_jota_rabbitmq_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy